from enum import Enum
class ResponseSignal(Enum):
 FILE_VALIDATED_SUCCESS = "file_validate_successfully"
 FILE_TYPE_NOT_SUPPORTED = "file_type_not_supported"
 FILE_SIZE_EXCEEDED = "file_size_exceeded"
 FILE_UPLOAD_SUCCESS = "file_upload_success"
 FILE_UPLOAD_FAILED = "file_upload_failed"
 PROCESSING_SUCCESS = "processing_success"
 PROCESSING_FAILED = "processing_failed"
 NO_FILES_ERROR = "not_found_files"
 FILE_ID_ERROR = "NO_FILE_FOUND_WITH_THIT_ID"
 PROJECT_NOT_FOUND_ERROR = "PROJECT_NOT_FOUND_ERROR"
 INSERT_INTO_VECTOR_DB_ERROR = "index_into_vector_db_ERROR"
 INSERT_INTO_VECTOR_DB_SUCCESS = "index_into_vector_db_SUCCESS"
 VECTORDB_COLLECTION_RETRIEVED = "vectordb_collection_retrieved"
 VECTORDB_SEARCH_ERROR = "vectordb_search_error"
 VECTORDB_SEARCH_SUCCESS = "vectordb_search_success"
 RAG_ANSWER_ERROR = "rag_answer_error"
 RAG_ANSWER_SUCCESS = "rag_answer_success"
